name: Hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
